yaml-files:
  - '*.yaml'
  - '*.yml'

# https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default

ignore:
  - 'testdata/envoy-snapshots/testdata/snapshots/*.yaml'
  - 'testdata/envoy-snapshots/testdata/portforward-mappings/*.yaml'
  - 'test/e2e/output/*.yaml'

rules:
  line-length: disable
  document-start: disable
  comments:
    level: error
  comments-indentation:
    level: error
  truthy:
    level: error
