# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  e2e:
    taskfile: ./test/e2e/Taskfile.yaml
    dir: ./test/e2e
  snapshot:
    taskfile: ./test/snapshot/Taskfile.yaml
    dir: ./test/snapshot

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/kubectl-localmesh main.go

  test:
    desc: Run tests
    cmds:
      - go test -cover ./...

  lint:
    desc: Run Linters
    cmds:
      - yamllint -c .yamllint.yaml .
      - golangci-lint run

  format:
    desc: Format code
    cmds:
      - gofmt -w .
