# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  e2e:
    taskfile: ./test/e2e/Taskfile.yaml
    dir: ./test/e2e

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/kubectl-localmesh main.go

  test:
    desc: Run tests
    cmds:
      - go test -cover ./...

  lint:
    desc: Run Linters
    cmds:
      - yamllint -c .yamllint.yaml .
      - golangci-lint run

  format:
    desc: Format code
    cmds:
      - gofmt -w .

  test:snapshot:
    desc: Run snapshot tests for Envoy configuration
    cmds:
      - testdata/envoy-snapshots/scripts/run-snapshots.sh

  test:update-snapshots:
    desc: Update Envoy config snapshot files (use carefully!)
    cmds:
      - task build
      - testdata/envoy-snapshots/scripts/update-snapshots.sh
