# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  e2e:
    taskfile: ./test/e2e/Taskfile.yaml
    dir: ./test/e2e
  snapshot:
    taskfile: ./test/snapshot/Taskfile.yaml
    dir: ./test/snapshot

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/kubectl-localmesh main.go

  test:
    desc: Run tests
    cmds:
      - go test -cover ./...

  lint:
    desc: Run Linters
    cmds:
      - yamllint -c .yamllint.yaml .
      - golangci-lint run

  install:
    desc: Install the binary to $GOBIN
    vars:
      GIT_VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
      GIT_COMMIT:
        sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
      BUILD_DATE:
        sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
    cmds:
      - go clean -i .
      - |
        go install -trimpath -v \
          -ldflags="-X main.version={{.GIT_VERSION}} -X main.commit={{.GIT_COMMIT}} -X main.date={{.BUILD_DATE}}" \
          .

  format:
    desc: Format code
    cmds:
      - gofmt -w .
